dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=^6.0
    - LARAVEL=^7.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=^6.0
    - php: 7.1
      env: LARAVEL=^7.0
  allow_failures:
    - env: LARAVEL=^7.0

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest
